[workspace]
members = [
    "lib",
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
# alloy-sol-types = "0.7.7"

# [package]
# name = "zkvm"
# version = "0.1.0"
# edition = "2021"

# [dependencies]
# alloy-sol-types = "0.7.7"