[package]
version = "0.1.0"
name = "block-proof-program"
edition = "2021"

[dependencies]
# alloy-sol-types = "0.6.0"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
block-proof-lib = { path = "../lib" }
